### ISSUE TITLE
Check for Scala module wrt Gradle module metadata fails due to Scala module build not adding GMM

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-integration-tests#6]
As things are, Scala module does not yet contain Gradle 6 module metadata:

https://github.com/FasterXML/jackson-module-scala/issues/478

mostly since it is built using `sbt` and adding support may not be feasible right now. Assuming this cannot be done in timeframe for Jackson 2.12, it probably makes sense to change `GradleTest` to exclude Scala module from tests.

I also realized that Scala 2.10 is no longer supported with Jackson 2.12, will remove that for now.

**Comment by cowtowncoder** [comment]
@jjohannes WDYT?

**Comment by cowtowncoder** [comment]
Looks like failure was only due to Scala module for Scala 2.10 (which was dropped in time for 2.12.0-rc2), commenting that out made the test pass, so this might not be problematic.
Leaving open for now, just in case.

**Comment by jjohannes** [comment]
Thanks for analysing this @cowtowncoder.

The test was indeed failing only because _Scala 2.10_ support was dropped. So we not testing that anymore is the right call.

That the Scala libraries do not publish the `module` file is indeed not a problem in practice at the moment. That is, because if a Jackson module that has a dependency like this:

`com.fasterxml.jackson:some-module:VERSION` ->  `com.fasterxml.jackson.core:jackson-core:VERSION`

Jackson Core will also bring in the BOM with version `VERSION`. And in total this will align to the right version.

This is probably true for many Jackson modules actually. Still I think it is good that we publish the `module` file with the BOM dependency for as many as we can, for consistency and also for addressing other use cases in the future.

I think you can close this issue. We can keep https://github.com/FasterXML/jackson-module-scala/issues/478. I will answer there as well.

**Comment by cowtowncoder** [comment]
Thank you @jjohannes -- that makes sense. And I agree, some level of redundancy is good for coverage and testing; users sometimes have incomplete dependencies and I assume overlapping definitions might help there.
Will close the issue.
