### ISSUE TITLE
Failed gradle/gmm tests for patch versions (2.12.1+)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-integration-tests#8]
Looks like gradle test `com.fasterxml.jackson.integtest.gradle.GradleTest` fails, both for `master` branch (now for Jackson 2.13.0-SNAPSHOT) and `2.12` (for latest stable patch release). For some reason the logic seems to always look for the last published version, but even there is something that throws it off.

I am not sure I understand the logic it tries to apply, but ideally it would be good to look for alignment of specific version as defined by test project's dependencies (or, if it must, explicit parameterization) -- and not what happens to be the latest externally available version.

@jjohannes I was hoping you could help here as you set up the test: I released 2.12.2 and was hoping to verify that the released jars have all the metadata correct. But now I cannot seem to get the test to pass at all.

**Comment by jjohannes** [comment]
@cowtowncoder thanks for letting me know. I just checked the test locally here and it is working fine. According to the error I found, it couldn't find some artefacts on Central, maybe those were not available yet? Or we were just unlucky and there as a connection issue with Central:

https://travis-ci.com/github/FasterXML/jackson-integration-tests/builds/219138425#L3211 

The test always tests against the latest release. IIRC we decided against testing snapshots because they are sometimes incomplete (not all modules are always available). So we said it's enough to have the test ensure that the latest release works.

You do not need to update anything in the repo when you do a new release. The test uses `latest.release` as version in the test build, which is a Gradle feature to always query the repository for the latest released version.

Maybe you can just reactivate the test and give it another try.

**Comment by cowtowncoder** [comment]
Ok I'll try it and see.

But one quick question: no problems wrt SNAPSHOT (I remember that being discussed), but just one more question -- on latest release, does that align with minor version? It's really valuable to be able to verify maintenance branches as well, and not just the latest stable branch. But from your description it sounds like it would only work for the latest released non-snapshot version?

If so, it seems that the test should be `@Ignore`d on all but one branch of this project?
For example: right now `master` points to 2.13 versions to help check compatibility across upcoming 2.13.0 -- but no version yet exist, so I'd guess it would try against 2.12.2.
Since integration test package is new, there isn't `2.11` branch; but if one existed, that, too, should not have the test enabled.
Or alternatively test may be left enabled but adds no value (and takes some time) to do the same test from all branches?

**Comment by cowtowncoder** [comment]
Ok it does now pass. Odd... I wonder if the issues with JAX-RS provider releases might matter here?

https://github.com/FasterXML/jackson-jaxrs-providers/issues/138

Looking at successful run output that must be the reason as jax-rs providers are included.

Ok. So at this point, things are working but it would be nice to have some way of doing something like this:

1. GradleTest for version compatibility is always enabled, for all branches, but...
2. It checks to see where version of test project has same minor version matches that of latest released minor version
3. If versions match (ignore patch version), run tests; if not, print a message that explains discrepancy, skips test

I don't know if this is possible but it would be good.

**Comment by jjohannes** [comment]
@cowtowncoder happy to hear that it works at least for now. I am sure we can make it better.

Can you clarify:

> It checks to see where version of test project has same minor version matches that of latest released minor version

I am not sure what's the version of "test project" here? The version that is in the [POM of this repository](https://github.com/FasterXML/jackson-integration-tests/blob/master/pom.xml#L31)? Because that's always set to the next `SNAPSHOT`, right?

**Comment by cowtowncoder** [comment]
There are multiple branches of `jackson-integration-tests` (right now just 2.12 and `master`, but eventually should match number of actively maintained Jackson branches). All/most of those would typically point to SNAPSHOT dependencies within matching minor branch, except temporarily if used to verify goodness of recently made release.

**Comment by jjohannes** [comment]
@cowtowncoder so IIUC, as long as the branch points to `2.12.x`, we run the test for the latest 2.12.x release (because it is the latest release). On other branches, which point to another minor version (like `master` right now), we do not run the test.

This should work: https://github.com/FasterXML/jackson-integration-tests/pull/9

**Comment by cowtowncoder** [comment]
Excellent, merged the PR.
